In [2]:
!pip install pandas
!pip install altair

Requirement already satisfied: pandas in ./venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in ./venv/lib/python3.14/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting altair
  Using cached altair-6.2.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: jinja2 in ./venv/lib/python3.14/site-packages (from altair) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in ./venv/lib/python3.14/site-packages (from altair) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in ./venv/lib/python3.14/site-packages (from altair) (2.22.1)
Requirement already satisfied: packaging in ./venv/lib/python3.14/site-packages (from altair) (26.2)
Requirement already satisfied: typing-extensions>=4.12.0 in ./venv/lib/python3.14/site-packages (from altair) (4.15.0)
Requirement already satisfied: attrs>=22.2.0 in ./venv/lib/python3.14/site-packages (from jsonschema>=3.0->altair) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./venv/lib/python3.14/site-packages (from jsonschema>=3.0->altair) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./venv/lib/python3.14/site-packages (from jsonschema>=3.0->altair) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in ./venv/lib/python3.14/site-packages (from jsonschema>=3.0->altair) (2026.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.14/site-packages (from jinja2->altair) (3.0.3)
Using cached altair-6.2.1-py3-none-any.whl (797 kB)
Installing collected packages: altair
Successfully installed altair-6.2.1

# Decomposition Experiments

## Heightfield dimensions

In [55]:
import pandas as pd

data = pd.read_csv('./timeResults2D/results.csv')
data['Time per Particle'] = data['Time']/data['Particles'] 
data

   Heightfield Dimensions  Particles    Time  Time per Particle
0                     350    1529075  133194           0.087108
1                     300    1120414   93306           0.083278
2                     250     775251   55890           0.072093
3                     200     493312   31552           0.063960
4                     150     274996   15235           0.055401
5                     100     119998    5532           0.046101
6                      50      28567    1025           0.035881

In [56]:
import altair as alt
base = alt.Chart(data).mark_line(point=alt.OverlayMarkDef(filled=False, fill="white")).encode(
    x=alt.X('Particles:Q', title=''),
    y=alt.Y('Time:Q', title='Time (ms)'),
    tooltip= ['Particles:N', alt.Tooltip('Time:Q', title='Time (ms)')],
).properties(
    title='Particles vs Time'
)
base

alt.Chart(...)

In [57]:

base = alt.Chart(data).mark_line(point=alt.OverlayMarkDef(filled=False, fill="white")).encode(
    x=alt.X('Heightfield Dimensions:Q', title=''),
    y=alt.Y('Particles:Q', title='Particles'),
    tooltip= ['Particles:N', alt.Tooltip('Time:Q', title='Time (ms)')],
).properties(
    title='Dimensions vs Particles'
)
base

alt.Chart(...)

In [58]:



base = alt.Chart(data).mark_line(point=alt.OverlayMarkDef(filled=False, fill="white")).encode(
    x=alt.X('Heightfield Dimensions:Q', title=''),
    y=alt.Y('Time:Q', title='Time (ms)'),
    tooltip= ['Particles:N', alt.Tooltip('Time:Q', title='Time (ms)')],
).properties(
    title='Particles vs Time'
)
base

alt.Chart(...)

In [59]:



base = alt.Chart(data).mark_line(point=alt.OverlayMarkDef(filled=False, fill="white")).encode(
    x=alt.X('Heightfield Dimensions:Q', title=''),
    y=alt.Y('Time per Particle:Q', title='ms/particle'),
    tooltip= ['Particles:N', alt.Tooltip('Time:Q', title='Time (ms)')],
).properties(
    title='Dimensions vs Time per Particle'
)
base

alt.Chart(...)

## zSamples

In [52]:
data = pd.read_csv('./timeResultsZ/results.csv')
data["Time per Particle"] = data["Time"]/data["Particles"]
data

   zSamples  Particles   Time  Time per Particle
0        10     286195  24706           0.086326
1        20     493312  31615           0.064087
2        30     700357  38354           0.054763
3        40     907749  45180           0.049771
4        50    1114983  52677           0.047245
5        99    2129585  90759           0.042618

In [53]:



base = alt.Chart(data).mark_line(point=alt.OverlayMarkDef(filled=False, fill="white")).encode(
    x=alt.X('zSamples:Q', title=''),
    y=alt.Y('Time per Particle:Q', title='Time (ms)'),
    tooltip= ['Particles:N', alt.Tooltip('Time:Q', title='Time (ms)')],
).properties(
    title='zSamples vs Time per Particle'
)
base

alt.Chart(...)

## Rugosity

## Multi-Resolution